<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.2" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.*" />
    <PackageReference Include="System.ServiceModel.Federation" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BaseSource\3.EndPoints\BaseSource.EndPoint\BaseSource.EndPoint.csproj" />
    <ProjectReference Include="..\..\1.Core\TK.Core.ApplicationService\TK.Core.ApplicationService.csproj" />
    <ProjectReference Include="..\..\1.Core\TK.Core.Domain\TK.Core.Domain.csproj" />
    <ProjectReference Include="..\..\2.Infrastructure\TK.Infrastructure.Data.Sql.Command\TK.Infrastructure.Data.Sql.Command.csproj" />
    <ProjectReference Include="..\..\2.Infrastructure\TK.Infrastructure.Data.Sql.Query\TK.Infrastructure.Data.Sql.Query.csproj" />
  </ItemGroup>

</Project>
