<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\Extensions\SharedKernel.Extensions.Providers\SharedKernel.Extensions.Providers.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\Extensions\SharedKernel.Extensions.Utilities\SharedKernel.Extensions.Utilities.csproj" />
    <ProjectReference Include="..\BaseSource.Core.Domain\BaseSource.Core.Domain.csproj" />
  </ItemGroup>

</Project>
